"""Add paid_at field to PaymentLink

Revision ID: 477e3eb9e659
Revises: 7ad89f951fc7
Create Date: 2025-10-21 22:16:33.079600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477e3eb9e659'
down_revision = '7ad89f951fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
