"""Add client_name to PaymentLink

Revision ID: 7ad89f951fc7
Revises: 
Create Date: 2025-10-21 21:20:10.613275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad89f951fc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=True))
    
    # Then update all existing rows to have a default value
    op.execute("UPDATE payment_link SET client_name = 'Client' WHERE client_name IS NULL")
    
    # Finally alter the column to be NOT NULL
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.alter_column('client_name', existing_type=sa.String(length=100), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
